# Dask

Dask performs two different tasks:
1. it optimizes dynamic task scheduling, similar to [Airflow](https://airflow.apache.org/), [Luigi](https://github.com/spotify/luigi) or [Celery](https://docs.celeryq.dev/en/stable/).
2. it performs parallel data like arrays, dataframes, and lists with dynamic task scheduling.

## Scales from laptops to clusters

Dask can be installed on a laptop with uv and expands the size of the datasets from *fits in memory* to *fits on disk*. Dask can also scale to a cluster of hundreds of machines. It is resilient, elastic, data-local and has low latency. For more information, see the [distributed scheduler](https://distributed.dask.org/en/latest/) documentation. This simple transition between a single machine and a cluster allows users to both start easily and grow as needed.

## Install Dask

You can install everything that is required for most common applications of Dask (arrays, dataframes, …). This installs both Dask and dependencies such as NumPy, Pandas, etc. that are required for various workloads:

``` bash
$ uv add "dask[complete]"
```

However, only individual subsets can be installed with:

``` bash
$ uv add "dask[array]"
$ uv add "dask[dataframe]"
$ uv add "dask[diagnostics]"
$ uv add "dask[distributed]"
```

## Familiar operation

### Dask DataFrame

… imitates pandas.

In [1]:
import pandas as pd


df = pd.read_csv("tutorials.csv")
grouped = df.groupby("Title")
grouped.agg("mean")

                  Unnamed: 0  2021-12  2022-01  2022-02
Title
Jupyter Tutorial         0.5  18103.5  20505.5  13099.0
PyViz Tutorial           2.0   4873.0   3930.0   2573.0
Python Basics            4.5    261.0    251.0    341.0

In [2]:
import dask.dataframe as dd


df = dd.read_csv("tutorials.csv")
grouped = df.groupby("Title")
grouped.agg("mean").head()

                  Unnamed: 0  2021-12  2022-01  2022-02
Title
Jupyter Tutorial         0.5  18103.5  20505.5  13099.0
PyViz Tutorial           2.0   4873.0   3930.0   2573.0
Python Basics            4.5    261.0    251.0    341.0

<div class="alert alert-block alert-info">

**See also:**

* [Dask DataFrame Docs](https://docs.dask.org/en/latest/dataframe.html)
* [Dask DataFrame Best Practices](https://docs.dask.org/en/latest/dataframe-best-practices.html)
</div>

### Dask Array

… imitates NumPy.

In [3]:
import h5py
import numpy as np


f = h5py.File("mydata.h5")
x = np.array(f["."])

In [4]:
import dask.array as da


f = h5py.File("mydata.h5")
x = da.array(f["."])

<div class="alert alert-block alert-info">

**See also:**

* [Dask Array Docs](https://docs.dask.org/en/latest/array.html)
* [Dask Array Best Practices](https://docs.dask.org/en/latest/array-best-practices.html)
</div>

### Dask Bag

… imitates [iterators](https://docs.python.org/3/library/itertools.html), [Toolz](https://toolz.readthedocs.io/en/latest/index.html) und [PySpark](https://spark.apache.org/docs/latest/api/python/).

In [5]:
import dask.bag as db


b = db.from_sequence([10, 3, 5, 7, 11, 4])
list(b.topk(2))

[11, 10]

<div class="alert alert-block alert-info">

**See also:**

* [Dask Bag Docs](https://docs.dask.org/en/latest/bag.html)
</div>

### Dask Delayed

… imitates loops and wraps custom code, see [Creating a delayed pipeline](../clean-prep/dask-pipeline.ipynb#5.-Creating-a-delayed-pipeline).

<div class="alert alert-block alert-info">

**See also:**

* [Dask Delayed Docs](https://docs.dask.org/en/latest/delayed.html)
* [Dask Delayed Best Practices](https://docs.dask.org/en/latest/delayed-best-practices.html)
* [Dask pipeline example: Tracking the International Space Station with Dask](../clean-prep/dask-pipeline.ipynb)
</div>

## `concurrent.futures`

… extends Python’s `concurrent.futures` interface and enables the submission of user-defined tasks.

<div class="alert alert-block alert-info">

**Note:**

For the following example, Dask must be installed with the `distributed` option, for example

``` bash
$ uv add dask[distributed]
```
</div>

In [6]:
from dask.distributed import Client

In [7]:
client = Client()

This starts local workers as processes.  To run the local workers as threads, you can pass `processes=False` as a parameter:

``` python
client = Client(processes=False)
```

Now you can execute your own tasks and chain dependencies using the `submit` method:

In [8]:
from math import pi


def inc(x):
    return x + 1


def circumference(x):
    return 2 * pi * x


increments = client.submit(inc, 10)
circumferences = client.submit(circumference, increments)

In [9]:
circumferences.result()

69.11503837897544

<div class="alert alert-block alert-info">

**See also:**

* [Dask Futures Docs](https://docs.dask.org/en/latest/futures.html)
* [Dask Futures Quickstart](https://distributed.dask.org/en/latest/quickstart.html)
* [Dask Futures Examples](https://examples.dask.org/futures.html)
</div>