# Selecting and filtering data

Indexing series `(obj[...])` works similarly to indexing NumPy arrays, except that you can use index values of the series instead of just integers. Here are some examples:

In [1]:
import numpy as np
import pandas as pd

In [2]:
idx = pd.date_range("2022-02-02", periods=7)
rng = np.random.default_rng()
s = pd.Series(rng.random(7), index=idx)

In [3]:
s

2022-02-02    0.472935
2022-02-03    0.872472
2022-02-04    0.875741
2022-02-05    0.348128
2022-02-06    0.713738
2022-02-07    0.119012
2022-02-08    0.509543
Freq: D, dtype: float64

In [4]:
s["2022-02-03"]

np.float64(0.8724721164207767)

In [5]:
s.iloc[1]

np.float64(0.8724721164207767)

In [6]:
s[2:4]

2022-02-04    0.875741
2022-02-05    0.348128
Freq: D, dtype: float64

In [7]:
s[["2022-02-04", "2022-02-03", "2022-02-02"]]

2022-02-04    0.875741
2022-02-03    0.872472
2022-02-02    0.472935
dtype: float64

In [8]:
s.iloc[[1, 3]]

2022-02-03    0.872472
2022-02-05    0.348128
Freq: 2D, dtype: float64

In [9]:
s[s > 0]

2022-02-02    0.472935
2022-02-03    0.872472
2022-02-04    0.875741
2022-02-05    0.348128
2022-02-06    0.713738
2022-02-07    0.119012
2022-02-08    0.509543
Freq: D, dtype: float64

Although this allows you to select data by label, the preferred method for selecting index values is the `loc` operator:

In [10]:
s.loc[["2022-02-04", "2022-02-03", "2022-02-02"]]

2022-02-04    0.875741
2022-02-03    0.872472
2022-02-02    0.472935
dtype: float64

The reason for preferring `loc` lies in the different treatment of integers when indexing with `[]`. In regular `[]` based indexing, integers are treated as labels if the index contains integers, so the behaviour differs depending on the data type of the index. In our example, the expression `s.loc[[3, 2, 1]]` will fail because the index does not contain integers:

In [11]:
s.loc[[3, 2, 1]]

KeyError: "None of [Index([3, 2, 1], dtype='int64')] are in the [index]"

Während der `loc`-Operator ausschließlich Label indiziert, indiziert der `iloc`-Operator ausschließlich mit ganzen Zahlen:

In [12]:
s.iloc[[3, 2, 1]]

2022-02-05    0.348128
2022-02-04    0.875741
2022-02-03    0.872472
Freq: -1D, dtype: float64

Ihr könnt auch mit Labels slicen, aber das funktioniert anders als das normale Python-Slicing, da der Endpunkt inklusive ist:

In [13]:
s.loc["2022-02-03":"2022-02-04"]

2022-02-03    0.872472
2022-02-04    0.875741
Freq: D, dtype: float64

Durch die Einstellung mit diesen Methoden wird der entsprechende Abschnitt der Reihe geändert:

In [14]:
s.loc["2022-02-03":"2022-02-04"] = 0

s

2022-02-02    0.472935
2022-02-03    0.000000
2022-02-04    0.000000
2022-02-05    0.348128
2022-02-06    0.713738
2022-02-07    0.119012
2022-02-08    0.509543
Freq: D, dtype: float64

Die Indizierung in einem DataFrame dient dazu, eine oder mehrere Spalten entweder mit einem einzelnen Wert oder einer Folge abzurufen:

In [15]:
data = {
    "Code": ["U+0000", "U+0001", "U+0002", "U+0003", "U+0004", "U+0005"],
    "Decimal": [0, 1, 2, 3, 4, 5],
    "Octal": ["001", "002", "003", "004", "004", "005"],
    "Key": ["NUL", "Ctrl-A", "Ctrl-B", "Ctrl-C", "Ctrl-D", "Ctrl-E"],
}

df = pd.DataFrame(data)
df = pd.DataFrame(data, columns=["Decimal", "Octal", "Key"], index=df["Code"])

df

        Decimal Octal     Key
Code
U+0000        0   001     NUL
U+0001        1   002  Ctrl-A
U+0002        2   003  Ctrl-B
U+0003        3   004  Ctrl-C
U+0004        4   004  Ctrl-D
U+0005        5   005  Ctrl-E

In [16]:
df["Key"]

Code
U+0000       NUL
U+0001    Ctrl-A
U+0002    Ctrl-B
U+0003    Ctrl-C
U+0004    Ctrl-D
U+0005    Ctrl-E
Name: Key, dtype: object

In [17]:
df[["Decimal", "Key"]]

        Decimal     Key
Code
U+0000        0     NUL
U+0001        1  Ctrl-A
U+0002        2  Ctrl-B
U+0003        3  Ctrl-C
U+0004        4  Ctrl-D
U+0005        5  Ctrl-E

Die Zeilenauswahlsyntax `df[:2]` wird aus Gründen der Bequemlichkeit bereitgestellt. Durch die Übergabe eines einzelnen Elements oder einer Liste an den `[]`-Operator werden Spalten ausgewählt.

In [18]:
df[:2]

        Decimal Octal     Key
Code
U+0000        0   001     NUL
U+0001        1   002  Ctrl-A

Ein weiterer Anwendungsfall ist die Indizierung mit einem booleschen DataFrame, der beispielsweise durch einen Skalarvergleich erzeugt wird:

In [19]:
df["Decimal"] > 2

Code
U+0000    False
U+0001    False
U+0002    False
U+0003     True
U+0004     True
U+0005     True
Name: Decimal, dtype: bool

In [20]:
df[df["Decimal"] > 2]

        Decimal Octal     Key
Code
U+0003        3   004  Ctrl-C
U+0004        4   004  Ctrl-D
U+0005        5   005  Ctrl-E

You can also combine these Boolean DataFrames using bitwise operators:

In [21]:
df[(df["Decimal"] > 2) & (df["Decimal"] < 5)]

        Decimal Octal     Key
Code
U+0003        3   004  Ctrl-C
U+0004        4   004  Ctrl-D

In [22]:
df[(df["Decimal"] < 3) | (df["Decimal"] > 4)]

        Decimal Octal     Key
Code
U+0000        0   001     NUL
U+0001        1   002  Ctrl-A
U+0002        2   003  Ctrl-B
U+0005        5   005  Ctrl-E

Like Series, DataFrame also has special operators `loc` and `iloc` for label-based and integer indexing, respectively. Since DataFrame is two-dimensional, you can select a subset of rows and columns using NumPy-like notation by using either axis labels (`loc`) or integers (`iloc`).

In [23]:
df.loc["U+0002", ["Decimal", "Key"]]

Decimal         2
Key        Ctrl-B
Name: U+0002, dtype: object

In [24]:
df.iloc[[2], [1, 2]]

       Octal     Key
Code
U+0002   003  Ctrl-B

In [25]:
df.iloc[[0, 1], [1, 2]]

       Octal     Key
Code
U+0000   001     NUL
U+0001   002  Ctrl-A

Both indexing functions work with slices in addition to individual labels or lists of labels:

In [26]:
df.loc[:"U+0003", "Key"]

Code
U+0000       NUL
U+0001    Ctrl-A
U+0002    Ctrl-B
U+0003    Ctrl-C
Name: Key, dtype: object

In [27]:
df.iloc[:3, :3]

        Decimal Octal     Key
Code
U+0000        0   001     NUL
U+0001        1   002  Ctrl-A
U+0002        2   003  Ctrl-B

There are many ways to select and rearrange the data contained in a pandas object. Below is a brief summary of most of these options for DataFrames:

Type | Note
:--- | :---
`df[LABEL]` | selects a single column or a sequence of columns from the DataFrame
`df.loc[LABEL]` | selects a single row or a subset of rows from the DataFrame by label
`df.loc[:, LABEL]` | selects a single column or a subset of columns from the DataFrame by Label
`df.loc[LABEL1, LABEL2]` | selects both rows and columns by label
`df.iloc[INTEGER]` | selects a single row or a subset of rows from the DataFrame by integer position
`df.iloc[INTEGER1, INTEGER2]` | selects a single column or a subset of columns by integer position
`df.at[LABEL1, LABEL2]` | selects a single value by row and column label
`df.iat[INTEGER1, INTEGER2]` | selects a scalar value by row and column position (integers)
`reindex NEW_INDEX` | selects rows or columns by label
`get_value`, `set_value` | deprecated since version 0.21.0: use `.at[]` or `.iat[]` instead.